import java.awt.*;
import java.awt.event.*;
import java.applet.Applet;
public class PaintingApp extends Applet{
	Button cirB, rectB, lineB, penB, eraserB, rb, yb, gb, bb, blackb, fillB;
	public void init(){
		cirB= new Button("Circle");
		rectB= new Button("Rectangle");
		lineB= new Button("Line");
		penB= new Button("Pen");
		eraserB= new Button("Eraser");
		rb= new Button("Red");
		yb= new Button("Yellow");
		gb= new Button("Green");
		bb= new Button("Blue");
		blackb= new Button("Black");
		fillB= new Button("Fill");
		add(cirB);
		add(rectB);
		add(lineB);
		add(penB);
		add(eraserB);
		add(rb);
		add(yb);
		add(gb);
		add(bb);
		add(blackb);
		add(fillB);
	}
	public void paint(Graphics g) {
		int width = getSize().width;   
     		int height = getSize().height;
		g.setColor(Color.white);
     		g.fillRect(0,0, width, height);
		g.setColor(Color.black);
      		g.drawRect(0, 0, width-1, height-1);
		g.drawRect(1, 1, width-3, height-3);
		g.drawRect(2, 2, width-5, height-5);
		g.drawRect(3, 3, width-7, height-7);
		cirB.setBackground(Color.gray);
		cirB.setForeground(Color.white);
		rectB.setBackground(Color.gray);
		rectB.setForeground(Color.white);
		lineB.setBackground(Color.gray);
		lineB.setForeground(Color.white);
		rb.setBackground(Color.red);
		rb.setForeground(Color.white);
		yb.setBackground(Color.yellow);
		yb.setForeground(Color.white);
		gb.setBackground(Color.green);
		gb.setForeground(Color.white);
		bb.setBackground(Color.blue);
		bb.setForeground(Color.white);
		blackb.setBackground(Color.black);
		blackb.setForeground(Color.white);
		cirB.setSize(width/9,height/10);
		cirB.setLocation(5,5);
		rectB.setSize(width/9,height/10);
		rectB.setLocation((width/9)+5,5);
		lineB.setSize(width/9,height/10);
		lineB.setLocation(2*(width/9)+5,5);
		penB.setSize(width/9,height/10);
		penB.setLocation(3*(width/9)+5,5);
		fillB.setSize(width/9,height/10);
		fillB.setLocation(4*(width/9)+5,5);
		eraserB.setSize(width/9,height/10);
		eraserB.setLocation(5*(width/9)+5,5);
		rb.setSize((width/9),height/20);
		rb.setLocation(6*(width/9)+5,5);
		yb.setSize((width/9),height/20);
		yb.setLocation(7*(width/9),5);
		gb.setSize((width/9),height/20);
		gb.setLocation(6*(width/9)+5,(height/20)+5);
		bb.setSize((width/9),(height/20)+5);
		bb.setLocation(7*(width/9),height/20);
		blackb.setSize((width/9),height/10);
		blackb.setLocation(8*(width/9)-2,5);
	}
}